### ISSUE TITLE
Support for 5.15.3 (it's released for opensource last year)

### ISSUE THREAD

**Issue by lkmikkel** [miurahr/aqtinstall#668] opened 2023-04-03 14:42 UTC
Hi,

Thanks for this software.

**Is your feature request related to a problem? Please describe.**
There is a bug in 5.15.2 that has been fixed in 5.15.3

**Describe the solution you'd like**
Is it possible to add support for Qt 5.15.3? It was finally released as opensource last year (a year behind commercial release).

**Comment by miurahr** [comment] 2023-04-04 04:45
Qt 5.15.3 is not supported by aqt,  because there are no package files for the version  which can be handled by aqtinstall.
There also no source package files that is supported by aqtinstall.  The packages are provided by Qt project/The Qt company, not by aqtinstall project.

You may not find any binary package files in https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/ for version 5.15.3.

You can still install from source manually from https://download.qt.io/archive/qt/5.15/5.15.3/single/ using your web browser,  and build it by your own using C++ compiler of your own.  aqtinstall tool and dev community does not help any of it.

**Comment by pzhlkj6612** [comment] 2023-04-04 13:55
Duplicate of #572. See also #636.

**Closed** 2023-04-06 05:02 UTC
Labels: duplicate, enhancement, wontfix
