### ISSUE TITLE
mingw11 installation for QT6

### ISSUE THREAD

**Issue by atsju** [miurahr/aqtinstall#697] opened 2023-07-31 15:58 UTC
**Is your feature request related to a problem? Please describe.**
I implemented CI on project https://github.com/githubdoe/DFTFringe using aqt and QT5 because history.
Now I want to try to move from QT5 to QT6 and I see that I cannot install the correct mingw 11.2.0 with aqt.

**Describe the solution you'd like**
Is it possible that aqt install supports the tools like mingw11 ?

**Describe alternatives you've considered**
I'm open to alternatives if you have some

**Additional context**
Followup of #655 
mingw version: https://wiki.qt.io/MinGW

**Comment by ddalcino** [comment] 2023-07-31 16:05
https://aqtinstall.readthedocs.io/en/latest/getting_started.html#installing-tools

> Please be aware that the tool tools_mingw90 appears to be mislabelled:

```
$ aqt list-tool windows desktop tools_mingw90 -l

   Tool Variant Name            Version          Release Date
=============================================================
qt.tools.win64_mingw900   9.0.0-1-202203221220   2022-03-22

$ aqt list-tool windows desktop tools_mingw90 -l

   Tool Variant Name            Version          Release Date      Display Name            Description
============================================================================================================
qt.tools.win64_mingw900   9.0.0-1-202203221220   2022-03-22     MinGW 11.2.0 64-bit   MinGW-builds 11.2.0
```

Duplicate of #655.

**Comment by atsju** [comment] 2023-07-31 16:22
owww... sorry. I did not see that 900 was indeed 11.2.0. Thanks a lot

**Closed** 2023-07-31 16:22 UTC
Labels: enhancement
