### ISSUE TITLE
aqtinstall does not work when https://download.qt.io is not available

### ISSUE THREAD

**Issue by gfx756** [miurahr/aqtinstall#519] opened 2022-04-26 12:53 UTC
Hello! When https://download.qt.io is not available it is not possible to use mirrors from the settings.ini config to list available tools:

```
$ aqt list-tool linux desktop
'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aqt/installer.py", line 108, in run
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/aqt/installer.py", line 540, in run_list_tool
    show_list(meta)
  File "/usr/local/lib/python3.8/dist-packages/aqt/metadata.py", line 775, in show_list
    output = meta.getList()
  File "/usr/local/lib/python3.8/dist-packages/aqt/metadata.py", line 435, in getList
    return self._action()
  File "/usr/local/lib/python3.8/dist-packages/aqt/metadata.py", line 482, in fetch_tools
    return list(MetadataFactory.iterate_folders(html_doc, "tools"))
  File "/usr/local/lib/python3.8/dist-packages/aqt/metadata.py", line 600, in iterate_folders
    for row in soup.body.table.find_all("tr"):
AttributeError: 'NoneType' object has no attribute 'find_all'
aqtinstall(aqt) v2.1.0 on Python 3.8.10 [CPython GCC 9.4.0]
Working dir: `/home/user`
Arguments: `['/usr/local/bin/aqt', 'list-tool', 'linux', 'desktop']` Host: `uname_result(system='Linux', node='laptop', release='5.13.0-40-generic', version='#45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022', machine='x86_64', processor='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.
```

Is it possible to use aqtinstall with mirrors when https://download.qt.io is not available?

**Comment by gfx756** [comment] 2022-04-26 12:58
I've tried to replace https://download.qt.io in the baseurl and trusted_mirrors parameters of settings.ini and use the --base command line argument to use a mirror but it have not helped.

**Comment by ddalcino** [comment] 2022-04-26 14:24
The stacktrace looks like it could be a duplicate of #517, which already has a fix in the master branch. Can you please try again with the master branch? I don't think there's been a release yet that includes the patch.

If setting the urls to something else doesn't work, please post the stacktrace/error messages here; I would like to see them.

**Comment by ddalcino** [comment] 2022-04-26 14:35
After a brief review of the code, it looks like the list-* commands are not capable of setting the base url via CLI argument. This has consequences: at least one install-tool command allows setting base url via CLI argument, and calls MetadataFactory functions, which do not respect the chosen base url. This will need to be fixed.

**Closed** 2022-06-01 00:09 UTC
Labels: bug, good first issue, no-issue-activity
