### ISSUE TITLE
Failed to install Qt 6.3.2 for Android

### ISSUE THREAD

**Issue by igormironchik** [miurahr/aqtinstall#562] opened 2022-09-12 10:04 UTC
**Describe the bug**
Failed to install Qt 6.3.2 for Android

**To Reproduce**
1. aqt install-qt linux android 6.3.2 android -m all

**`aqt` output**
Add program output to help explain your problem.

```
aqt install-qt linux android 6.3.2 android -m all
INFO    : aqtinstall(aqt) v2.2.3 on Python 3.10.4 [CPython GCC 11.2.0]
WARNING : Specified Qt version is unknown: 6.3.2.
ERROR   : 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 108, in run
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 312, in run_install_qt
    qt_archives = retry_on_bad_connection(
  File "/usr/local/lib/python3.10/dist-packages/aqt/helper.py", line 165, in retry_on_bad_connection
    return function(base_url)
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 313, in <lambda>
    lambda base_url: QtArchives(
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 292, in __init__
    self._get_archives()
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 359, in _get_archives
    self._get_archives_base(f"qt{self.version.major}_{self._version_str()}{self._arch_ext()}", self._target_packages())
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 383, in _get_archives_base
    self._parse_update_xml(os_target_folder, update_xml_text, target_packages)
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 404, in _parse_update_xml
    for archive in packageupdate.downloadable_archives:
TypeError: 'NoneType' object is not iterable
ERROR   : aqtinstall(aqt) v2.2.3 on Python 3.10.4 [CPython GCC 11.2.0]
Working dir: `/home/igor/Qt`
Arguments: `['/usr/local/bin/aqt', 'install-qt', 'linux', 'android', '6.3.2', 'android', '-m', 'all']` Host: `uname_result(system='Linux', node='gmi', release='5.15.0-47-generic', version='#51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022', machine='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.
```

**Desktop (please complete the following information):**
 - OS: linux
 - `aqt` version aqtinstall(aqt) v2.2.3 on Python 3.10.4 [CPython GCC 11.2.0]

**Comment by ddalcino** [comment] 2022-09-12 15:59
Thanks for reporting this; it’s definitely a UI bug that we will need to address.

For now, please be aware that android` is not a valid argument for the `arch` parameter in this case. Please see the docs at https://aqtinstall.readthedocs.io/en/latest/getting_started.html#installing-qt-for-android to find out what you should be doing differently.

**Comment by igormironchik** [comment] 2022-09-12 16:08
Thanks for your answer. You are right, this is just a UI issue.

Could you answer, on the following command line:

```
aqt install-doc linux 6.3.2 -m all
```

I've got:

```
INFO    : aqtinstall(aqt) v2.2.3 on Python 3.10.4 [CPython GCC 11.2.0]
WARNING : Specified Qt version is unknown: 6.3.2.
ERROR   : 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 108, in run
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 424, in run_install_doc
    self._run_src_doc_examples("doc", args)
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 377, in _run_src_doc_examples
    srcdocexamples_archives: SrcDocExamplesArchives = retry_on_bad_connection(
  File "/usr/local/lib/python3.10/dist-packages/aqt/helper.py", line 165, in retry_on_bad_connection
    return function(base_url)
  File "/usr/local/lib/python3.10/dist-packages/aqt/installer.py", line 378, in <lambda>
    lambda base_url: SrcDocExamplesArchives(
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 518, in __init__
    super(SrcDocExamplesArchives, self).__init__(
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 292, in __init__
    self._get_archives()
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 359, in _get_archives
    self._get_archives_base(f"qt{self.version.major}_{self._version_str()}{self._arch_ext()}", self._target_packages())
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 383, in _get_archives_base
    self._parse_update_xml(os_target_folder, update_xml_text, target_packages)
  File "/usr/local/lib/python3.10/dist-packages/aqt/archives.py", line 404, in _parse_update_xml
    for archive in packageupdate.downloadable_archives:
TypeError: 'NoneType' object is not iterable
ERROR   : aqtinstall(aqt) v2.2.3 on Python 3.10.4 [CPython GCC 11.2.0]
Working dir: `/home/igor/Tmp`
Arguments: `['/usr/local/bin/aqt', 'install-doc', 'linux', '6.3.2', '-m', 'all']` Host: `uname_result(system='Linux', node='gmi', release='5.15.0-47-generic', version='#51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022', machine='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.
```

I don;t think that in this case this is only a UI error.

**Comment by ddalcino** [comment] 2022-09-12 19:36
Interesting. I will have to look at this after work. I don’t think you did anything wrong here.

Qt 6.3.2 looks like it was released within the past 2 days. You might be the first person to install it with aqtinstall. It’s likely that something at download.qt.io has changed.

**Comment by ddalcino** [comment] 2022-09-13 14:15
I’ve had a look at the code, and I think this is a new bug introduced by #533. That PR removed a filter for empty DownloadUpdate xml tags, and I think that’s causing this problem. I think that what we really need to do is add a test case for empty DownloadUpdate tags; that would have prevented this regression to begin with.

I have not checked this yet, but I’m pretty sure that aqtinstall v2.1.0 handles both problems here properly. For the install-doc command, it should just skip over the empty tag. For the install-qt command, it should fail gracefully and suggest that you run `aqt list-qt` to list valid architectures.

There’s a case to be made here that instead of suggesting that you run list-qt, aqt should just run the appropriate list-qt command automatically and tell you exactly what you did wrong and how to fix it. That’s probably a separate issue though, and I don’t know if there’s time to handle it before v3 is released.

**Closed** 2022-09-23 03:01 UTC
Labels: bug
