### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""

### ISSUE THREAD

**Issue by MartinDelille** [miurahr/aqtinstall#100] opened 2020-02-27 16:25 UTC
I installed Qt 5.12.7 with `aqt install 5.12.7 mac desktop` and installed *Qt Creator* via [Homebrew](https://brew.sh) (`brew cask install qt-creator`).

I configured *Qt Creator* kits to use the one install via `aqt` and I can compile a simple widget project.

Unfortunately, I have the following error when starting it in debug mode:

```
QFactoryLoader::QFactoryLoader() checking directory path "/Users/martin/dev/build/pouet/Qt_5_12_7_clang_64_from_aqt/Debug/pouet.app/Contents/MacOS/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

The program has unexpectedly finished.
```

`QT_DEBUG_PLUGINS` is set to `1` as adviced here: https://forum.qt.io/topic/98816/qt-could-not-find-the-platform-plugin-cocoa/8

Any idea what's going on?

**Comment by miurahr** [comment] 2020-02-27 22:51
It seems installed at "5.12.7/clang_64/plugins/platforms/' please check in your installation.
The package seems https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638qtbase-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z

**Comment by MartinDelille** [comment] 2020-03-05 16:27
It seems that the `platforms` directory is ok:

```
$ls /path/to/aqt/5.12.7/clang_64/plugins/platforms/
libqcocoa.dylib
libqcocoa_debug.dylib
libqminimal.dylib
libqminimal_debug.dylib
libqoffscreen.dylib
libqoffscreen_debug.dylib
```

**Comment by MartinDelille** [comment] 2020-03-06 09:58
Ok sorry the problem doesn't come from `aqt` but from the *Qt Creator* version installed with *Homebrew cask*

**Comment by MartinDelille** [comment] 2020-03-10 09:55
Ok I tried with an official installer downloaded from The Qt Company and compiled and run a basic widget project with two kit:

1. The one configured automatically (5.12.6)
2. The one configured manually by selecting the `qmake` binary install with `aqt`

I only have the error in the second case.

I'm really interested in `aqt` so I'll be happy to dig more into this problem. Could you reopen the issue?

**Comment by miurahr** [comment] 2020-03-11 03:59
@MartinDelille Could you check configuration file in installation folder?

Aqt does not support any scripting  by installscript.qs  qscript which is inside meta package.
https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_5127/qt.qt5.5127.clang_64/5.12.7-0-202001290638meta.7z

Aqt only manipulate qconfig.pri "QT_EDITION=OpenSource"

```
/****************************************************************************
**
** Copyright (C) 2018 The Qt Company Ltd.
** Contact: https://www.qt.io/licensing/
**
** This file is part of the release tools of the Qt Toolkit.
**
** $QT_BEGIN_LICENSE:GPL-EXCEPT$
** Commercial License Usage
** Licensees holding valid commercial Qt licenses may use this file in
** accordance with the commercial license agreement provided with the
** Software or, alternatively, in accordance with the terms contained in
** a written agreement between you and The Qt Company. For licensing terms
** and conditions see https://www.qt.io/terms-conditions. For further
** information use the contact form at https://www.qt.io/contact-us.
**
** GNU General Public License Usage
** Alternatively, this file may be used under the terms of the GNU
** General Public License version 3 as published by the Free Software
** Foundation with exceptions as appearing in the file LICENSE.GPL3-EXCEPT
** included in the packaging of this file. Please review the following
** information to ensure the GNU General Public License requirements will
** be met: https://www.gnu.org/licenses/gpl-3.0.html.
**
** $QT_END_LICENSE$
**
****************************************************************************/

// constructor
function Component()
{
    if (installer.value("XCodeChecked") == false) {
        var xcodeVersion = installer.execute("/usr/bin/xcodebuild", new Array("-version"))[0];
        if (!xcodeVersion) {
            QMessageBox["warning"]("XcodeError",
                qsTr("Xcode installation not found!"),
                qsTr("You need to install Xcode and set up Xcode command line tools. Download Xcode from https://developer.apple.com\n"));
        }
    }
    installer.setValue("XCodeChecked", true)

    // Determine if this is a online snapshot build

    var snapshotBuild = false;
    var isSnapshotStr = "false";
    if (['true', 'yes', '1'].indexOf(isSnapshotStr) >= 0)
        snapshotBuild = true;

    if (snapshotBuild) {
        // Add automatic dependency for preview component
        var autoDependency = component.value("AutoDependOn");
        var dependencyStr = "preview.qt.qt5.512.clang_64";
        if (autoDependency)
            component.setValue("AutoDependOn", autoDependency + "," + dependencyStr)
        else
            component.setValue("AutoDependOn", dependencyStr)
    }
}

function setSnapShotBuild()
{
    var snapshotBuild = false;
    var isSnapshotStr = "false";
    if (['true', 'yes', '1'].indexOf(isSnapshotStr) >= 0)
        snapshotBuild = true;

    if (snapshotBuild) {
        // Add automatic dependency for preview component
        var autoDependency = component.value("AutoDependOn");
        var dependencyStr = "preview.qt.qt5.512.clang_64";
        if (autoDependency)
            component.setValue("AutoDependOn", autoDependency + "," + dependencyStr)
        else
            component.setValue("AutoDependOn", dependencyStr)
    }
}

Component.prototype.createOperations = function()
{
    component.createOperations();
    try {
        var qtPath = "@TargetDir@" + "/5.12.7/clang_64";
        var qmakeBinary = "@TargetDir@" + "/5.12.7/clang_64/bin/qmake";
        addInitQtPatchOperation(component, "mac", qtPath, qmakeBinary, "qt5");

        if (installer.value("SDKToolBinary") == "")
            return;

        component.addOperation("Execute",
                               ["@SDKToolBinary@", "addQt",
                                "--id", component.name,
                                "--name", "Qt %{Qt:Version} clang 64bit",
                                "--type", "Qt4ProjectManager.QtVersion.Desktop",
                                "--qmake", qmakeBinary,
                                "UNDOEXECUTE",
                                "@SDKToolBinary@", "rmQt", "--id", component.name]);

        var kitName = component.name + "_kit";
        component.addOperation("Execute",
                               ["@SDKToolBinary@", "addKit",
                                "--id", kitName,
                                "--name", "Desktop Qt %{Qt:Version} clang 64bit",
                                "--Ctoolchain", "x86-macos-generic-mach_o-64bit",
                                "--Cxxtoolchain", "x86-macos-generic-mach_o-64bit",
                                "--qt", component.name,
                                "--debuggerengine", "256", // DebuggerEngineType::LldbEngineType
                                "--devicetype", "Desktop",
                                "UNDOEXECUTE",
                                "@SDKToolBinary@", "rmKit", "--id", kitName]);

        // patch/register docs and examples
        var installationPath = installer.value("TargetDir") + "/5.12.7/clang_64";
        print("Register documentation and examples for: " + installationPath);
        patchQtExamplesAndDoc(component, installationPath, "Qt-5.12.7");

        // is this OpenSource installation?
        var isOpenSource = "true";
        if (['true', 'yes', '1'].indexOf(isOpenSource) >= 0) {
            // patch qconfig.pri
            var qconfigFile = qtPath + "/mkspecs/qconfig.pri";
            component.addOperation("LineReplace", qconfigFile, "QT_EDITION =", "QT_EDITION = OpenSource");
            component.addOperation("LineReplace", qconfigFile, "QT_LICHECK = licheck_mac", "QT_LICHECK =");
        }

        // QTBUG-37650
        patchQtAssistant(component, installationPath, "Qt-5.12.7");

    } catch(e) {
        print(e);
    }
}

//QTBUG-37650
function patchQtAssistant(aComponent, aComponentRootPath, aQtInstallationName)
{
    if (installer.value("os") == "mac") {
        print("Patching qt.conf for Assistant to: " + aComponentRootPath);
        var fileName = aComponentRootPath + "/bin/Assistant.app/Contents/Resources/" + "qt.conf";
        print("qt.conf file: " + fileName);

        aComponent.addOperation("Settings",
            "path=" + fileName,
            "method=add_array_value",
            "key=Paths/Prefix",
            "value=../../..");

        aComponent.addOperation("Settings",
        "path=" + fileName,
        "method=add_array_value",
        "key=Paths/Documentation",
        "value=../../Docs/" + aQtInstallationName);
    }
}
```

**Comment by MartinDelille** [comment] 2020-03-11 09:49
> @MartinDelille Could you check configuration file in installation folder?

Which file do you want me to check? What do you want me to check?

**Comment by miurahr** [comment] 2020-03-11 12:48
- which file
  qt.conf
  qconfig.pri
- what
 difference between official installation and aqt.

**Comment by MartinDelille** [comment] 2020-03-12 16:22
`qt.conf` differ only this way:

```
$ diff /path/to/official/Qt/5.12.6/clang_64/bin/qt.conf /path/to/aqt/5.12.6/clang_64/bin/qt.conf            5.3s
2,3d1
< Documentation=../../Docs/Qt-5.12.6
< Examples=../../Examples/Qt-5.12.6
```

`qconfig.pri` are identical.

**Comment by miurahr** [comment] 2020-03-14 08:10
Thank @MartinDelille for your report.
The difference is exactly a following script doing.
```
//QTBUG-37650
function patchQtAssistant(aComponent, aComponentRootPath, aQtInstallationName)
{
    if (installer.value("os") == "mac") {
        print("Patching qt.conf for Assistant to: " + aComponentRootPath);
        var fileName = aComponentRootPath + "/bin/Assistant.app/Contents/Resources/" + "qt.conf";
        print("qt.conf file: " + fileName);

        aComponent.addOperation("Settings",
            "path=" + fileName,
            "method=add_array_value",
            "key=Paths/Prefix",
            "value=../../..");

        aComponent.addOperation("Settings",
        "path=" + fileName,
        "method=add_array_value",
        "key=Paths/Documentation",
        "value=../../Docs/" + aQtInstallationName);
    }
```
And it seems not related to the issue qt.qpa.plugin, because[QTBUG-37650](https://bugreports.qt.io/browse/QTBUG-37650) title is "Mac: No documentation in Qt Assistant"

**Comment by miurahr** [comment] 2020-03-14 08:19
When referring similar bug report  [QTBUG-80563](https://bugreports.qt.io/browse/QTBUG-80563), reporter diagnose an environment with environment variable "QT_DEBUG_PLUGINS=1" .

Does it help us to know what happened under the hood?

**Comment by MartinDelille** [comment] 2020-03-27 06:21
The `QT_DEBUG_PLUGINS=1` environment variable is already set since I run my app in debug mode.

I put the run log here: https://github.com/miurahr/aqtinstall/issues/100#issue-572197109

**Comment by MartinDelille** [comment] 2020-04-27 09:43
@miurahr sorry to ping you, but since this issue has been mark as stale, I wondered if you had any idea on how I could go on with this issue?

**Comment by miurahr** [comment] 2020-04-29 23:38
@MartinDelille I have no idea. I don't have a machine to reproduce and I don't know what happened here. Everything aqtinstall should do seems to be done well.

**Comment by miurahr** [comment] 2020-04-30 00:04
@MartinDelille Could you check your application folders whether "cocoa" plugin file is placed in your application distribution and configured correctly?
There is a environment variable QT_PLUGIN_PATH which may affect application.

**Comment by agateau** [comment] 2020-05-05 07:59
I hit a similar issue when running tests and found two ways to workaround it.

## First approach
This is a workaround. Create a file named `qt.conf` next to the test binary with the following content:
```
[Paths]
Prefix=/full/path/to/qt/installation/prefix
```
Prefix should include to the `clang_64` directory.

## Second approach
This is a more "correct" fix. When Qt installer installs the libraries, it patches :scream_cat: the `qmake` and `QtCore` binaries at install time, or at least it did [until Qt 5.15.0](https://www.qt.io/blog/qt-is-relocatable).

I created a script to do the same thing: https://gist.github.com/agateau/f217cebd8b645b1c7466d233e1f1fcfb.

You can call this script after using `aqtinstall`, passing it the installation prefix.

If this works for you I can look into creating a PR to integrate this to aqtinstall.

**Comment by miurahr** [comment] 2020-05-06 06:10
> If this works for you I can look into creating a PR to integrate this to aqtinstall.

@MartinDelille how?

**Comment by MartinDelille** [comment] 2020-05-06 13:42
Thanks @agateau for looking into this!

> Create a file named qt.conf next to the test binary with the following content

What do you mean by *test binary*?

**Comment by MartinDelille** [comment] 2020-05-06 13:45
(sorry I think you mean `/Users/martin/dev/build/pouet/Qt_5_12_7_clang_64_from_aqt/Debug/pouet.app/Contents/MacOS/pouet` in my case.

**Comment by agateau** [comment] 2020-05-06 21:44
Yes, that's what I meant, though it have to go in another directory of the bundle in your case (my test binary was not in a bundle, and I am not on the Mac at the moment)

**Comment by agateau** [comment] 2020-05-09 09:36
For the record, right now I have found that define `QT_PLUGIN_PATH` is enough and less intrusive. This is what I am currently doing in a template I am creating to build Qt apps (https://github.com/agateau/cookiecutter-qt-app/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/ci/install-dependencies#L47)

**Comment by MartinDelille** [comment] 2020-05-09 12:14
It works!!!

Thank you so much for your kind help! In order to make it work for [my project](https://github.com/MartinDelille/chat-qt/), I had to add the following three environment variables at runtime:

```
export QT_PLUGIN_PATH=/path/to/qt/x.x.x/clang_64/plugins/
export QML_IMPORT_PATH=/path/to/qt/x.x.x/clang_64/qml/
export QML2_IMPORT_PATH=/path/to/qt/x.x.x/clang_64/qml/
```

The most acceptable fix for my problem would be to have this variable defined automatically. in Qt Creator project run settings when selecting this kit. I would say that patching `qmake` is not a good idea.

**Comment by miurahr** [comment] 2020-05-09 13:05
Now here is a solution. close here.

**Comment by MartinDelille** [comment] 2020-05-18 08:32
This is not a solution, just a work around. I would let the issue open.

**Comment by miurahr** [comment] 2020-05-18 11:46
> If this works for you I can look into creating a PR to integrate this to aqtinstall.

OK, I'd like to wait PR.

**Comment by miurahr** [comment] 2020-05-19 04:02
From [my posted code](https://github.com/miurahr/aqtinstall/issues/100#issuecomment-597432472)
does these chunk doing an operation which @agateau described?

```
        var qtPath = "@TargetDir@" + "/5.12.7/clang_64";
        var qmakeBinary = "@TargetDir@" + "/5.12.7/clang_64/bin/qmake";
        addInitQtPatchOperation(component, "mac", qtPath, qmakeBinary, "qt5");
```

Does anyone knows a way how to call qscript function from python?

**Comment by miurahr** [comment] 2020-05-19 05:35
It seems defined as

```
addInitQtPatchOperation = function(aComponent, aOS, aQtPath, aQmakePath, version)
{
    aComponent.addOperation("ConsumeOutput", qmakeOutputInstallerKey(aComponent), aQmakePath, "-query");
    aComponent.addOperation("QtPatch", aOS, aQtPath, version);
}
```

and 'QtPath' can be found at [installer framework](https://github.com/qtproject/installer-framework/blob/master/src/libs/installer/qtpatch.cpp)

**Comment by miurahr** [comment] 2020-05-19 06:41
It seems be a thing what @agateau doing in https://gist.github.com/agateau/f217cebd8b645b1c7466d233e1f1fcfb

**Comment by miurahr** [comment] 2020-05-19 11:19
I just found similar tweaks are also done for windows.

```
    if (installer.value("os") == "win") {
        try {
            var qtPath = "@TargetDir@" + "/5.14.2/msvc2017_64";
            var qmakeBinary = "@TargetDir@" + "/5.14.2/msvc2017_64/bin/qmake.exe";
            addInitQtPatchOperation(component, "windows", qtPath, qmakeBinary, "qt5");
```

**Comment by miurahr** [comment] 2020-05-19 22:57
I found another fact.

A following chunk in initscript.qs
```
 if (installer.value("SDKToolBinary") == "")
            return;

        component.addOperation("Execute",
                               ["@SDKToolBinary@", "addQt",
                                "--id", component.name,
                                "--name", "Qt %{Qt:Version} clang 64bit",
                                "--type", "Qt4ProjectManager.QtVersion.Desktop",
                                "--qmake", qmakeBinary,
                                "UNDOEXECUTE",
                                "@SDKToolBinary@", "rmQt", "--id", component.name]);

        var kitName = component.name + "_kit";
        component.addOperation("Execute",
                               ["@SDKToolBinary@", "addKit",
                                "--id", kitName,
                                "--name", "Desktop Qt %{Qt:Version} clang 64bit",
                                "--Ctoolchain", "x86-macos-generic-mach_o-64bit",
                                "--Cxxtoolchain", "x86-macos-generic-mach_o-64bit",
                                "--qt", component.name,
                                "--debuggerengine", "256", // DebuggerEngineType::LldbEngineType
                                "--devicetype", "Desktop",
                                "UNDOEXECUTE",
                                "@SDKToolBinary@", "rmKit", "--id", kitName]);
```
launches sdktool. which is [a part of QtCreator](https://github.com/qt-creator/qt-creator/blob/master/src/tools/sdktool/README.md). It is used to register qt sdk to qt creator configuration.

It may also affect for behavior of Qt Creator.

aqtinstall is created in order to use at CI environment, where user don't use qtcreator and where user cannot launch gui applications.

To make QtCreator working with aqtinstall, there need more and more work.
If anyone want to push PR, you are welcome.

**Comment by miurahr** [comment] 2020-05-21 03:37
#130 do patch to `qmake` with installed prefix path when target version is < 5.14.2 for Windows, Mac and Linux.

When installed on Mac OSX, it also patch `QtCore` and `QtCore_debug` in `QtCore.Framework` which is as same as @agateau  doing at https://gist.github.com/agateau/f217cebd8b645b1c7466d233e1f1fcfb

Qt 5.14.2, 5.15.0 and later does not have an entry point to patch.

Aqt will try patching when prefix path length is under 256 bytes. When a long path is specified, patching will be skipped to avoid breaking `qmake` binary. It also try keeping the `qmake` file permissions.

**Comment by miurahr** [comment] 2020-05-21 13:15
v0.9.0b3 is out with the fix.
@MartinDelille does v0.9.0b3 solves your issue?

**Comment by miurahr** [comment] 2020-05-31 08:35
v0.9.0 released with the fix.

**Closed** 2020-06-13 10:44 UTC
Labels: enhancement, feedback
