### ISSUE TITLE
Source "qtbase" archive not downloaded

### ISSUE THREAD

**Issue by martinrotter** [miurahr/aqtinstall#664] opened 2023-03-29 07:39 UTC
```
 INFO    : aqtinstall(aqt) v3.1.4 on Python 3.7.9 [CPython MSC v.1900 64 bit (AMD64)]
WARNING : The parameter 'target' with value 'desktop' is deprecated and marked for removal in a future version of aqt.
In the future, please omit this parameter.
INFO    : Downloading qtbase...
INFO    : Redirected: qt.mirror.constant.com
WARNING : Caught Bad7zFile, terminating installer workers
ERROR   : not a 7z file
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\installer.py", line 180, in run
    args.func(args)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\installer.py", line 514, in run_install_src
    self._run_src_doc_examples("src", args)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\installer.py", line 501, in _run_src_doc_examples
    run_installer(srcdocexamples_archives.get_packages(), base_dir, sevenzip, keep, _archive_dest)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\installer.py", line 1171, in run_installer
    raise e from e
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\aqt\installer.py", line 1130, in run_installer
    pool.starmap(installer, tasks)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
py7zr.exceptions.Bad7zFile: not a 7z file
ERROR   : aqtinstall(aqt) v3.1.4 on Python 3.7.9 [CPython MSC v.1900 64 bit (AMD64)]
Working dir: `D:\a\rssguard\rssguard`
Arguments: `['C:\\hostedtoolcache\\windows\\Python\\3.7.9\\x64\\Scripts\\aqt', 'install-src', '-O', 'D:\\a\\rssguard\\rssguard\\qt', 'windows', 'desktop', '6.4.3', '--archives', 'qtbase']` Host: `uname_result(system='Windows', node='fv-az41-649', release='10', version='10.0.17763', machine='AMD64', processor='Intel64 Family 6 Model 85 Stepping 7, GenuineIntel')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues
Please remember to include a copy of this program's output in your report.
INFO    : aqtinstall(aqt) v3.1.4 on Python 3.7.9 [CPython MSC v.1900 64 bit (AMD64)]
INFO    : Downloading qt.tools.openssl.win_x64...
INFO    : Redirected: qt.mirror.constant.com
INFO    : Finished installation of openssl_1.1.1q_prebuild_x64.7z in 3.94092350
INFO    : Finished installation
INFO    : Time elapsed: 5.91253290 second
```

**Comment by ddalcino** [comment] 2023-03-29 13:19
This is a duplicate of #662. The fix hasn't been released yet, but you can try the master branch and see if the fix works for you.

**Closed** 2023-03-30 06:08 UTC
Labels: bug
