### ISSUE TITLE
Wrong platform downloaded when requesting Qt 6.4.3 for Android in Linux

### ISSUE THREAD

**Issue by carlonluca** [miurahr/aqtinstall#666] opened 2023-03-31 22:30 UTC
**Describe the bug**
Apparently, aqt is downloading packages for the wrong platform when downloading Qt 6.4.3 for Android for Linux.
Please note that this is the first time I use aqt so I may be doing something wrong.

By using the same exact command (see below), I'm apparently getting the Android build for Linux when version is like 6.4.0, but for Windows when version is 6.4.3.

**To Reproduce**
1. Install aqt with `pip3 install aqtinstall`.
2. Run `aqt install-qt linux android 6.4.0 android_armv7 --autodesktop`, this is the output:

```
INFO    : aqtinstall(aqt) v3.1.5 on Python 3.10.6 [CPython GCC 11.3.0]
INFO    : You are installing the android version of Qt, which requires that the desktop version of Qt is also installed. Now installing Qt: desktop 6.4.0 gcc_64
INFO    : Downloading qtbase...
INFO    : Downloading qtdeclarative...
INFO    : Downloading qttools...
INFO    : Downloading qtsvg...
INFO    : Redirected: ftp.fau.de
INFO    : Redirected: ftp.fau.de
INFO    : Redirected: ftp.fau.de
INFO    : Redirected: ftp.fau.de
INFO    : Finished installation of qtsvg-Linux-RHEL_8_4-Clang-Android-Android_ANY-ARMv7.7z in 1.15756772
INFO    : Downloading qttranslations...
INFO    : Finished installation of qttools-Linux-RHEL_8_4-Clang-Android-Android_ANY-ARMv7.7z in 2.43259264
[...]
```

This seems reasonable.

4. Now run `aqt install-qt linux android 6.4.3 android_armv7 --autodesktop`. This is what I get:

```
INFO    : aqtinstall(aqt) v3.1.5 on Python 3.10.6 [CPython GCC 11.3.0]
INFO    : You are installing the android version of Qt, which requires that the desktop version of Qt is also installed. Now installing Qt: desktop 6.4.3 gcc_64
INFO    : Downloading qtdeclarative...
INFO    : Downloading qtsvg...
INFO    : Downloading qttools...
INFO    : Downloading qtbase...
INFO    : Redirected: ftp.fau.de
INFO    : Redirected: ftp.fau.de
INFO    : Redirected: ftp.fau.de
INFO    : Redirected: ftp.fau.de
INFO    : Finished installation of qtsvg-Windows-Windows_10_22H2-Clang-Android-Android_ANY-ARMv7.7z in 1.05883105
INFO    : Downloading qttranslations...
INFO    : Redirected: ftp.fau.de
INFO    : Finished installation of qttools-Windows-Windows_10_22H2-Clang-Android-Android_ANY-ARMv7.7z in 2.91395837
INFO    : Downloading qtbase...
INFO    : Redirected: ftp.fau.de
INFO    : Finished installation of qttranslations-Windows-Windows_10_22H2-Clang-Android-Android_ANY-ARMv7.7z in 4.16898553
```

This sounds weird, as the prefix seems to refer to Windows.

 - OS: Linux Ubuntu Jammy in a Docker container
 - `aqt` version: aqtinstall(aqt) v3.1.5 on Python 3.10.6 [CPython GCC 11.3.0]

**Comment by ddalcino** [comment] 2023-03-31 22:44
Duplicate of #621

Don't read too much into the filename, it looks like the binary was built on Windows, but it's cross-platform, and it will build your Android project just as well as the one built on RHEL.

**Comment by carlonluca** [comment] 2023-03-31 23:53
I suspected that, but I wasn't sure.
I suppose you can close the issue then. Thanks!

**Closed** 2023-04-01 00:06 UTC
Labels: duplicate, invalid, question
