### ISSUE TITLE
Trying to install it on windows I get the error: "No module named 'aqt.version'"

### ISSUE THREAD

**Issue by dgonzalezt** [miurahr/aqtinstall#564] opened 2022-09-15 11:51 UTC
Hi,

First of all I apologise, I think my problem is simply because I don't know how to use aqtinstall properly. I am trying to install it on windows. I just download aqt.exe and when I try to execute aqt in windows a get a error, any call to aqt gives the same error  (aqt help or aqt list-qt windows desktop).

Thanks in advance

```
C:\Users\Daniel\Downloads>aqt help
Traceback (most recent call last):
  File "daa144671dcb11ed_aqt.py", line 33, in <module>
  File "daa144671dcb11ed_aqt.py", line 25, in importlib_load_entry_point
  File "importlib\metadata.py", line 86, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "aqt\__init__.py", line 31, in <module>
ModuleNotFoundError: No module named 'aqt.version'
[11040] Failed to execute script 'daa144671dcb11ed_aqt' due to unhandled exception!

```

**Comment by miurahr** [comment] 2022-09-15 14:43
@dgonzalezt could you try older version of aqt.exe?

A build system for aqt.exe is broken in v2.2.2. It may fixed in v2.2.3, but may have defeat.
v2.2.1 seems working.

**Comment by dgonzalezt** [comment] 2022-09-16 08:53
Yes!!! V2.2.1 seems to works, 
thank you!.

**Comment by miurahr** [comment] 2022-09-16 11:58
When building `aqt.exe`
`pyproject.toml` is disabled in https://github.com/miurahr/aqtinstall/commit/f06707b37f45532f20353f7930bd6d5f8dc8658d
It is also disabled that generate `version.py` which carry version information, that is described only in `pyproject.toml` 

@nikitalita is it a correct investigation?

**Comment by miurahr** [comment] 2022-09-16 12:07
A previous version of setup.py contains:
```
setup(
    use_scm_version={
        "write_to": "aqt/version.py",
        "write_to_template": '__version__ = "{version}"\n',
        "tag_regex": r"^(?P<prefix>v)?(?P<version>[^\+]+)(?P<suffix>.*)?$",
        "local_scheme": "no-local-version",
    }
)
```
@nikitalita could you update build script of `aqt.exe` to change `setup.py` containing a block?

**Comment by miurahr** [comment] 2022-09-16 12:08
ref https://github.com/miurahr/aqtinstall/pull/557

**Comment by nikitalita** [comment] 2022-09-16 18:07
> A previous version of setup.py contains:
> 
> ```
> setup(
>     use_scm_version={
>         "write_to": "aqt/version.py",
>         "write_to_template": '__version__ = "{version}"\n',
>         "tag_regex": r"^(?P<prefix>v)?(?P<version>[^\+]+)(?P<suffix>.*)?$",
>         "local_scheme": "no-local-version",
>     }
> )
> ```
> 
> @nikitalita could you update `build_standalone.bat` to change `setup.py` containing a block?

can't, slammed right now.

**Comment by miurahr** [comment] 2022-09-18 04:09
A CI test passed so there may be a work around for it.
Is it possible to be two phase build?

**Comment by miurahr** [comment] 2022-09-18 09:26
After investigation of gravitygee and pyppyn code and understanding its legacy behaviors,  propose #565 that cheat gravitygee and pyppyn with pseudo launcher script.

The root cause is modern PIP with pyproject.toml does not generate launcher script any more. It produce only an app.exe file.
This is true reason why standalone build on v2.2.2 failed.

@nikitalita could you review or confirm #565 ?

**Closed** 2022-09-19 13:40 UTC
Labels: bug
