### ISSUE TITLE
Ubuntu: TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by TripleWhy** [miurahr/aqtinstall#98] opened 2020-02-26 13:55 UTC
I found this awesome project a few days ago, thank you very much for it. I tried it on windows with msys2, where everything works as expected. Now I tried to run it on a linux machine, but it didn't work. So I loaded a fresh Ubuntu 18.04.3 VM and tried it there, same result. I installed aqt via `pip3 install aqtinstall`. The error is the same for `install` and `tool`, but the output is shorter for tool, so I use that as an example. Any help would be appreciated.

```
$ pip3 show aqtinstall
Name: aqtinstall
Version: 0.7.4
...
$ aqt tool linux tools_ifw 3.2.0 qt.tools.ifw.32
2020-02-26 14:42:38,656 - aqt - WARNING - Specified target combination is not valid: linux tools_ifw qt.tools.ifw.32
2020-02-26 14:42:38,858 - aqt - INFO - Downloading https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/qt.tools.ifw.32/3.2.0ifw-linux-x64.7z...
2020-02-26 14:42:39,640 - aqt - INFO - Redirected to new URL: http://ftp.fau.de/qtproject/online/qtsdkrepository/linux_x64/desktop/tools_ifw/qt.tools.ifw.32/3.2.0ifw-linux-x64.7z
2020-02-26 14:42:42,066 - aqt - INFO - Extracting ifw-linux-x64.7z...
2020-02-26 14:42:42,084 - aqt - INFO - Downloads are Completed.
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
^C
```

**Comment by miurahr** [comment] 2020-02-27 04:49
It may related to #91

**Comment by altendky** [comment] 2020-02-27 05:05
I should have put a hash but that disappeared for me since the last release. Would have to check latest git commit when I posted this:

https://github.com/miurahr/aqtinstall/issues/91#issuecomment-589921412

**Comment by miurahr** [comment] 2020-02-27 14:44
I have changed multi-threading method in v0.8a1, which will be released soon.
Please wait and check it.

**Comment by miurahr** [comment] 2020-02-28 00:26
This may be caused by a change introduced in v0.7.2, because many users report v0.7.1 works fine.
I'd like to revert the change in v0.7.2 and is going to release it as v0.7.6.

**Comment by miurahr** [comment] 2020-03-09 07:49
Do @TripleWhy reproduce same error with #101 branch?

It drops ProcessPoolExecutor() that is related to pickling.
https://github.com/miurahr/aqtinstall/pull/101/files#diff-41b1cc84b9e7ecf03598fa01bf4afce2L103

Theoretically said, #101 will fix a issue "cannot pickle" error.

Detail: pickling is happened when python trying to start subprocess; pickling subroutine and spawn it in another python process. #101 switch to "multiprocessing.dummy" which is threading not subprocess, so it does not run pickling.

**Comment by miurahr** [comment] 2020-03-09 07:55
I can say same comment above on v0.8 series. @TripleWhy it is good chance to check v0.8a4, that is good enough, because github actions qt-install-actions switches it. 

v0.8 uses "ThreadPoolExecutor" instead of "ProcessPoolExecutor".

**Comment by TripleWhy** [comment] 2020-03-09 09:52
@miurahr I installed v0.8a4 via pip and that works, thanks.

**Closed** 2020-03-09 11:01 UTC
Labels: bug
