### ISSUE TITLE
Qt default installation directory (GUI installer)

### ISSUE THREAD

**Issue by asteinh** [miurahr/aqtinstall#48] opened 2019-10-15 06:49 UTC
When calling e.g.
```
C:\> aqt install --outputdir c:\Qt 5.11.3 windows desktop win64_msvc2017_64
```
I would expect the installed files (according to the readme) to end up in `C:\Qt\5.11.3`. However, I find them in `C:\Qt\Qt5.11.3\5.11.3` - not sure if that's intended behavior (then it should probably be stated in the readme) or a bug?

**Comment by miurahr** [comment] 2019-11-07 10:54
The issue is existed in https://github.com/miurahr/aqtinstall/blob/master/aqt/installer.py#L94
```
        if target_dir is not None:
-            base_dir = os.path.join(target_dir, 'Qt')
+           base_dir = target_dir
        else:
-            base_dir = os.path.join(os.getcwd(), 'Qt')
+           base_dir = os.getcwd()
```
may solve it.

**Comment by miurahr** [comment] 2019-11-10 06:33
Release v0.5b2 now released with the fix. Does it works for you?

With a command ` aqt install --outputdir tmp/Qt 5.11.3 windows desktop win64_msvc2017_64` in my linux desktop, I observed files in `tmp/Qt/5.11.3/msvc2017_64/[bin, lib..]`

**Comment by asteinh** [comment] 2019-11-10 06:57
This works like a charm, thanks for the fix!

**Closed** 2019-11-10 07:26 UTC
Labels: bug
